export const assets = {
    styles:
        [
            'static/css/ants.css',
        ],
    fonts:
        [
            '/static/fonts/dpcomic.ttf'
        ],
    images:
        [
            '/static/images/bonuses/bomb.png',
            '/static/images/bonuses/coin.png',
            '/static/images/bonuses/medkit.png',
            '/static/images/bonuses/puzzle.png',
            '/static/images/bonuses/batteries.png',
            '/static/images/bonuses/shield.png',
            '/static/icons/aim.png',
            '/static/icons/aimInv.png',
            '/static/icons/ant.png',
            '/static/images/wearetheants.png',
            '/static/icons/pause.png',
            '/static/icons/play.png',
            '/static/icons/playNext.png',
            '/static/icons/playPrevious.png',
            '/static/images/chars/rip.png',
            '/static/icons/stop.png',
            '/static/icons/volume.png',
            '/static/icons/charPicker.png',
            '/static/images/chars/commander/avatar.png',
            '/static/images/ants/queen.gif',
            '/static/images/ants/queen.png',
            '/static/images/ants/warrior.gif',
            '/static/images/ants/warrior.png',
            '/static/images/ants/worker.gif',
            '/static/images/ants/worker.png',
            '/static/images/bg/ants1.png',
            '/static/images/bg/ants2.png',
            '/static/images/bg/playingField.png',
            '/static/images/bg/desert.png',
            '/static/images/bg/mars.png',
            '/static/images/bg/poorGrass.png',
            '/static/images/bg/road.png',
            '/static/images/bg/sand.png',
            '/static/images/chars/crab/avatar.png',
            '/static/images/chars/crab/body.png',
            '/static/images/chars/crab/head.png',
            '/static/images/chars/crab/preview.png',
            '/static/images/chars/turtle/avatar.png',
            '/static/images/chars/turtle/body.png',
            '/static/images/chars/turtle/head.png',
            '/static/images/chars/turtle/preview.png',
            '/static/images/chars/ufo/avatar.png',
            '/static/images/chars/ufo/body.png',
            '/static/images/chars/ufo/head.png',
            '/static/images/chars/ufo/preview.png',
        ],
    scripts:
        [
            './sources/engine/game/level.js',
            './sources/engine/game/bonus.js',
            './sources/engine/game/levelLoop.js',
            './sources/engine/game/puzzle.js',
            './sources/engine/game/stateManager.js',
            './sources/engine/npc/ant.js',
            './sources/engine/npc/antColony.js',
            './sources/engine/physics/cpmovement.js',
            './sources/engine/physics/screen.js',
            './sources/engine/physics/shooting.js',
            './sources/engine/player/player.js',
            './sources/engine/player/abilities.js',
            './sources/engine/player/controls.js',
            './sources/ui/details/playerInfo.js',
            './sources/engine/sound/music.js',
            './sources/engine/misc.js',
            './sources/game/characters.js',
            './sources/game/declarations.js',
            './sources/game/bonuses.js',
            './sources/game/levels.js',
            './sources/engine/logging.js',
            './sources/ui/details/gameInfo.js',
            './sources/ui/details/playerControls.js',
            './sources/ui/menu/charMenu.js',
            './sources/ui/menu/endGameMenu.js',
            './sources/ui/menu/mainMenu.js',
            './sources/ui/menu/menu.js',
            './sources/ui/menu/pauseMenu.js',
            './sources/ui/broadcast.js',
            './sources/ui/elements.js',
            './sources/ui/gameInterface.js',
            './sources/ui/ui.js',
            './sources/game.js',
        ]
}

export const cssVariables = {
        '--tile-background': '/static/images/bg/ants1.png',
        '--tile-background2': '/static/images/bg/ants2.png',
        '--menu-item': '/static/icons/ant.png',
        '--we-are-the-ants': '/static/images/wearetheants.png',
        '--playingfiled-background': '/static/images/bg/playingField.png',
        '--charPicker': '/static/icons/charPicker.png',
        '--commander': '/static/images/chars/commander/avatar.png',
        '--cursor-aim': '/static/icons/aim.png',
        '--cursor-aim-green': '/static/icons/aimInv.png',
        '--player-rip': '/static/images/chars/rip.png',
        '--queen-skin': '/static/images/ants/queen.gif',
        '--warrior-skin': '/static/images/ants/warrior.gif',
        '--worker-skin': '/static/images/ants/worker.gif',
        '--queen-frozen': '/static/images/ants/queen.png',
        '--warrior-frozen': '/static/images/ants/warrior.png',
        '--worker-frozen': '/static/images/ants/worker.png',
}